window-padding-x = 0
window-padding-y = 0
window-padding-color = extend-always
background = #1B1818
cursor-color = #1B1818
background-opacity = 1
window-decoration = none
fullscreen = true
confirm-close-surface = false
