-- Hyprland theme colors - generated by theme-apply into
-- ~/.config/themes/current/hypr-colors.lua and loaded by hyprland.lua (via dofile).
return {
  active_border   = { "rgb({cyan.vivid_strip})", "rgb({accent.vivid_strip})", "rgb({magenta.vivid_strip})" },
  active_angle    = 90,
  inactive_border = "rgba({color8.strip}55)",
}
