# Yazi theme - generated by theme-apply

[mgr]
cwd = { fg = "{blue}" }

# Hovered
hovered = { fg = "{background}", bg = "{blue}" }
preview_hovered = { underline = true }

# Find
find_keyword = { fg = "{yellow}", italic = true }
find_position = { fg = "{cyan}", bg = "reset", italic = true }

# Marker
marker_copied = { fg = "{green}", bg = "{green}" }
marker_cut = { fg = "{red}", bg = "{red}" }
marker_marked = { fg = "{blue}", bg = "{blue}" }
marker_selected = { fg = "{cyan}", bg = "{cyan}" }

# Tab
tab_active = { fg = "{background}", bg = "{blue}" }
tab_inactive = { fg = "{color7}", bg = "{background}" }
tab_width = 1

# Count
count_copied = { fg = "{background}", bg = "{green}" }
count_cut = { fg = "{background}", bg = "{red}" }
count_selected = { fg = "{background}", bg = "{cyan}" }

# Border
border_symbol = "|"
border_style = { fg = "{blue}" }

# Highlighting
syntect_theme = ""

[mode]
normal_main = { fg = "{background}", bg = "{green}", bold = true }
normal_alt = { fg = "{green}", bg = "{color8}" }
select_main = { fg = "{background}", bg = "{cyan}", bold = true }
select_alt = { fg = "{cyan}", bg = "{color8}" }
unset_main = { fg = "{background}", bg = "{magenta}", bold = true }
unset_alt = { fg = "{magenta}", bg = "{color8}" }

[status]
separator_open = ""
separator_close = ""
separator_style = { fg = "{blue}", bg = "{blue}" }

# Progress
progress_label = { fg = "{color7}", bold = true }
progress_normal = { fg = "{green}", bg = "{background}" }
progress_error = { fg = "{red}", bg = "{background}" }

# Permissions
permissions_t = { fg = "{green}" }
permissions_r = { fg = "{cyan}" }
permissions_w = { fg = "{yellow}" }
permissions_x = { fg = "{blue}" }
permissions_s = { fg = "{color7}" }

[input]
border = { fg = "{blue}" }
title = {}
value = {}
selected = { reversed = true }

[completion]
border = { fg = "{blue}" }
active = { bg = "{blue}", fg = "{background}" }
inactive = {}

[tasks]
border = { fg = "{blue}" }
title = {}
hovered = { fg = "{green}" }

[which]
cols = 3
mask = { bg = "{background}" }
cand = { fg = "{cyan}" }
rest = { fg = "{color7}" }
desc = { fg = "{blue}" }
separator = "  "
separator_style = { fg = "{blue}" }

[help]
on = { fg = "{green}" }
run = { fg = "{cyan}" }
desc = { fg = "{color7}" }
hovered = { bg = "{blue}", bold = true }
footer = { fg = "{background}", bg = "{color7}" }

[filetype]
rules = [
  # Images
  { mime = "image/*", fg = "{cyan}" },

  # Videos
  { mime = "video/*", fg = "{magenta}" },
  { mime = "audio/*", fg = "{magenta}" },

  # Archives
  { mime = "application/*zip", fg = "{red}" },
  { mime = "application/*tar", fg = "{red}" },
  { mime = "application/*compressed", fg = "{red}" },

  # Documents
  { mime = "application/pdf", fg = "{yellow}" },
  { name = "*.md", fg = "{blue}" },

  # Code
  { name = "*.{js,ts,jsx,tsx}", fg = "{cyan}" },
  { name = "*.{py,pyc}", fg = "{green}" },
  { name = "*.{rs,toml}", fg = "{red}" },
  { name = "*.{sol,gleam}", fg = "{blue}" },

  # Directories
  { name = "*/", fg = "{blue}" },

  # Fallback
  { name = "*", fg = "{color7}" },
]

[icon]
rules = [
  { name = "*/", text = "" },
  { name = "*.rs", text = "" },
  { name = "*.py", text = "" },
  { name = "*.js", text = "" },
  { name = "*.ts", text = "" },
  { name = "*.sol", text = "󰞻" },
  { name = "*.md", text = "" },
  { name = "*.json", text = "" },
  { name = "*.toml", text = "" },
  { name = "*.yaml", text = "" },
  { name = "*.yml", text = "" },
]
