-- Hyprland configuration (Lua) - entry point.
-- Migrated from hyprland.conf (Hyprland 0.55+ Lua config). See TODO.md and the
-- migration plan for context.
--
-- RELOAD-CORRECTNESS: this entry chunk re-executes on `hyprctl reload`, while the
-- require()'d modules below are cached and run once. So mutable / theme-dependent work
-- (loading colors + the general{} block that holds col.active_border) lives HERE so a
-- reload repaints borders; one-time registration (events, submaps, binds, rules) lives
-- in the required modules so a reload cannot duplicate it.

local HOME = os.getenv("HOME")

-- Make the split modules under ./lua/ requireable by bare name.
package.path = (HOME .. "/.config/hypr/lua/?.lua;") .. package.path

--------------------------------------------------------------------------------
-- Environment variables
--------------------------------------------------------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

--------------------------------------------------------------------------------
-- Theme colors (generated by the theme engine -> ~/.config/themes/current/).
-- Loaded with dofile (NOT require) so `hyprctl reload` always re-reads fresh colors;
-- pcall-guarded with a fallback so a fresh clone (no generated file yet) still starts.
--------------------------------------------------------------------------------
local function load_theme()
  local ok, t = pcall(dofile, HOME .. "/.config/themes/current/hypr-colors.lua")
  if ok and type(t) == "table" then
    return t
  end
  return {
    active_border   = { "rgb(33ccff)", "rgb(00ff99)" },
    active_angle    = 45,
    inactive_border = "rgba(595959aa)",
  }
end
local theme = load_theme()

--------------------------------------------------------------------------------
-- General (holds the theme-driven border colors, so it lives in the entry).
--------------------------------------------------------------------------------
hl.config({
  general = {
    gaps_in  = 3,
    gaps_out = 3,

    border_size = 3,

    col = {
      active_border   = { colors = theme.active_border, angle = theme.active_angle },
      inactive_border = theme.inactive_border,
    },

    resize_on_border = false,
    allow_tearing    = false,

    layout = "dwindle",
  },
})

--------------------------------------------------------------------------------
-- Static modules (run once; survive reload via the require cache).
--------------------------------------------------------------------------------
require("monitors")
require("look")
require("input")
require("rules")
require("keybinds")
require("autostart")
