palette = "theme"

[palettes.theme]
background = "{background}"
foreground = "{foreground}"
black = "{color0}"
red = "{red}"
green = "{green}"
yellow = "{yellow}"
blue = "{blue}"
magenta = "{magenta}"
cyan = "{cyan}"
white = "{color7}"
bright-black = "{color8}"
bright-red = "{bright_red}"
bright-green = "{bright_green}"
bright-yellow = "{bright_yellow}"
bright-blue = "{bright_blue}"
bright-magenta = "{bright_magenta}"
bright-cyan = "{bright_cyan}"
bright-white = "{color15}"